apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e7ysu9h9q-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e7ysu9h9q-python 
  name: e7ysu9h9q-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: e7ysu9h9q-python 
